### ISSUE TITLE
How to deploy it to own server?

### ISSUE THREAD

**Issue by Xbot3maSter** [code-friends/CodeFriends#201]
Hi,i m using ubuntu system   compile it follow the instruction but this  command brew install mysql mongodb only for mac users not for linux ..
so how can install it?
And after npm started  server's   no ideo what's should i do the next?

**Comment by thejsj** [comment]
You can install mysql and mongodb in ubuntu using apt-get.

How to install MySQL: https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-on-ubuntu (Only step 2!)

How to install MongoDB (not used right now): https://www.digitalocean.com/community/tutorials/how-to-install-mongodb-on-ubuntu-14-04

How to install RethinkDB (currently used instead of MongoDB): http://rethinkdb.com/docs/install/ubuntu/

After you compile everything (`npm install` and `npm run bulid`) and you run `npm start`, your local server will be running in some port. I think it'll just be port 8000, but I'm not sure. The console will say. Then you go to `http://localhost:8000` in your browser and your app should be there.

**Comment by Xbot3maSter** [comment]
which files should i configure edit it.?

**Comment by Xbot3maSter** [comment]
i ve encounter this problem when start the server?
also localhost:8000 it just loading nothing show up

> CodeFriends@1.0.0 dev /root/Downloads/CodeFriends-master
> ./node_modules/nodemon/bin/nodemon.js --watch ./server server

27 Aug 15:48:27 - [nodemon] v1.4.1
27 Aug 15:48:27 - [nodemon] to restart at any time, enter `rs`
27 Aug 15:48:27 - [nodemon] watching: /root/Downloads/CodeFriends-master/server/**/*
27 Aug 15:48:27 - [nodemon] starting `node server`
config: { mysql: 
   { host: 'localhost',
     user: 'root',
     password: '',
     database: 'code_friends' },
  mongo: 'mongodb://127.0.0.1:27017/codeFriends?auto_reconnect',
  rethinkdb: { host: 'localhost', port: 28015, db: 'code_friends' },
  ports: { http: 8000, editor: 9000, chat: 9001, video: 8005 },
  url: '127.0.0.1',
  github: 
   { clientID: '364ea3bc2b086177fd27',
     clientSecret: '2dce4e81ad618474f5c822b4567200b941a6c1b1' },
  timeFormat: 'YYYY-MM-DDTHH:MM:SSZ',
  tmpDirectory: '../data/tmp',
  gitRepositoriesDirectory: '../data/git-repositories' }
Chat listening on port: 9001
Editor listening on port: 9000
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at EventEmitter.listen (/root/Downloads/CodeFriends-master/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/root/Downloads/CodeFriends-master/server/index.js:43:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
27 Aug 15:48:28 - [nodemon] app crashed - waiting for file changes before starting...

**Comment by Xbot3maSter** [comment]
i tried install  old package https://github.com/chaseme3/CodeFriends with mongodb 
also facing same error  start it how can i fix this.?

27 Aug 15:52:58 - [nodemon] v1.4.1
27 Aug 15:52:58 - [nodemon] to restart at any time, enter `rs`
27 Aug 15:52:58 - [nodemon] watching: *.*
27 Aug 15:52:58 - [nodemon] starting `node server`
editor listening on http://localhost:8007/
editor listening on http://localhost:8007/
Hello from Auth
got to projectRouter
/root/Downloads/cod3/node_modules/express/lib/router/route.js:196
        throw new Error(msg);
              ^
Error: Route.post() requires callback functions but got a [object Undefined]
    at Route.(anonymous function) [as post] (/root/Downloads/cod3/node_modules/express/lib/router/route.js:196:15)
    at Function.proto.(anonymous function) (/root/Downloads/cod3/node_modules/express/lib/router/index.js:510:19)
    at Object.<anonymous> (/root/Downloads/cod3/server/project/projectRoutes.js:7:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/root/Downloads/cod3/server/api.js:2:21)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/root/Downloads/cod3/server/index.js:83:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
27 Aug 15:53:02 - [nodemon] app crashed - waiting for file changes before starting...

**Comment by thejsj** [comment]
I tried to answer your question in the other thread. So I'm going to go ahead and close this one. Feel free to comment on the other issue.
